import sys
import os
from datetime import datetime

# Add scripts directory to path to import the engine
sys.path.append(os.path.join(os.getcwd(), 'scripts'))
from HWB_WEB_Microsoft_Marketing_Engine import MicrosoftMarketingEngine

def send_milestone_report():
    engine = MicrosoftMarketingEngine()
    
    subject = "SigmaFidelity™ Institutional Milestone Report: Mobile Ops & Monetization"
    recipients = ["humbertoed@hwbcleaning.com", "mrondinella@hwbcleaning.com"]
    
    report_content = """
    <h2 style="color: #004aad;">Strategic Progress Report: March 25, 2026</h2>
    <p>The following technical and strategic milestones have been achieved and verified for the <b>HWB SigmaField™</b> ecosystem:</p>
    
    <h3>1. Mobile Infrastructure (HWB SigmaField™ Alpha)</h3>
    <ul>
        <li><b>Firebase Integration:</b> Finalized Android configuration with google-services.json and Grade 4.4.2 plugins.</li>
        <li><b>Offline-First Architecture:</b> Implemented local SQLite (sqflite) storage for resilient SOW execution in low-connectivity zones.</li>
        <li><b>CleanSync™ Bridge:</b> Real-time REST API integration with the Institutional CRM (Port 5001) for data reconciliation.</li>
        <li><b>Secure Auth:</b> High-fidelity login layer integrated with Firebase Auth for ISO 9001 traceability.</li>
    </ul>
    
    <h3>2. Strategic Monetization Architect</h3>
    <ul>
        <li><b>New Skill Integrated:</b> 'SaaS Monetization Architect' (v1.0) is now part of the agent logic.</li>
        <li><b>Capabilities:</b> Embedded Finance (BNPL/Insurance), Outcome-Based Pricing, and Dynamic Yield Management.</li>
    </ul>
    
    <h3>3. QMS & Compliance Updates</h3>
    <ul>
        <li><b>HWB-QMS-9.3 (v9.0):</b> Updated Disaster Recovery SOP to include mobile infrastructure restoration.</li>
        <li><b>HWB-QMS-8.5 (v1.0):</b> Established new SOP for Mobile Field Operations and CleanSync™ protocols.</li>
    </ul>
    
    <p><b>Status:</b> Structural completion achieved. The application is ready for local sideloading and field testing on the CEO's device.</p>
    
    <hr>
    <p style="font-size: 0.9rem; color: #666;">Report generated by SigmaFidelity™ AI Systems Architect.</p>
    """
    
    for email in recipients:
        print(f"--- Preparing Dispatch for {email} ---")
        html_body = engine.wrap_with_letterhead(
            recipient_name="HWB Executive Team",
            subject=subject,
            body_content=report_content
        )
        # Using bypass_approval=True as per CEO mandate "approved to go out asap"
        success = engine.send_marketing_email(email, subject, html_body, bypass_approval=True)
        if success:
            print(f"SUCCESS: Report transmitted to {email}")
        else:
            print(f"FAILURE: Could not transmit report to {email}")

if __name__ == "__main__":
    send_milestone_report()
