"""
SigmaFidelity™ Enterprise 100% Hardening Verification Suite
Standard: HWB-QMS-7.6 Enterprise Architecture Standards (SOC 2 / ISO 27001)
"""

import sys
import os
import time

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "HWB-COMPANY", "HWB-IT", "HWB-IT-WEBSITE"))
sys.path.insert(0, BASE_DIR)

from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, "../../..", ".env"))

from main_app import app
from core.services.database import get_db, get_pool_status, PooledConnection
from core.services.rate_limiter import limiter, SlidingWindowRateLimiter
from core.services.task_queue import task_queue

def run_tests():
    print("=== [TEST SUITE] SigmaFidelity™ 100% Enterprise Hardening Verification ===")

    # 1. Test Threaded Database Connection Pooling
    print("\n--- 1. Testing Threaded Connection Pooling Engine ---")
    db_url = app.config['DATABASE_URL']
    
    conn1 = get_db(db_url)
    assert isinstance(conn1, PooledConnection), "get_db() did not return a PooledConnection instance!"
    with conn1.cursor() as cur:
        cur.execute("SELECT 1;")
        res = cur.fetchone()[0]
        assert res == 1, "Database query failed on pooled connection"
    conn1.close()
    assert conn1.closed, "PooledConnection failed to mark closed"
    print("✓ Test 1.1 PASS: PooledConnection acquired, executed query, and returned to pool cleanly.")

    pool_status = get_pool_status(db_url)
    assert pool_status.get('active_pools') >= 1, "No active connection pool reported"
    assert pool_status.get('min_conn') >= 1 and pool_status.get('max_conn') >= 10, "Pool size boundaries incorrect"
    print(f"✓ Test 1.2 PASS: Connection pool telemetry validated: {pool_status}")

    # Test concurrent rapid checkouts
    connections = []
    for _ in range(5):
        c = get_db(db_url)
        with c.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM \"Leads\";")
            cur.fetchone()
        connections.append(c)
    for c in connections:
        c.close()
    print("✓ Test 1.3 PASS: Rapid multi-connection checkout and return executed without socket leakage.")

    # 2. Test Rate Limiting Engine
    print("\n--- 2. Testing Rate Limiting & Abuse Defense Engine ---")
    test_limiter = SlidingWindowRateLimiter()
    test_key = "test_ip_192_168_1_1"

    # Allow 3 requests per 10 seconds
    allowed1, _ = test_limiter.is_allowed(test_key, limit=3, period_seconds=10)
    allowed2, _ = test_limiter.is_allowed(test_key, limit=3, period_seconds=10)
    allowed3, _ = test_limiter.is_allowed(test_key, limit=3, period_seconds=10)
    blocked, retry_after = test_limiter.is_allowed(test_key, limit=3, period_seconds=10)

    assert allowed1 and allowed2 and allowed3, "Legitimate requests incorrectly blocked by rate limiter!"
    assert not blocked, "4th request was not blocked when exceeding limit of 3!"
    assert retry_after > 0, "retry_after seconds must be > 0"
    print(f"✓ Test 2.1 PASS: Sliding window rate limiter allowed 3/3 and blocked 4th request (retry_after={retry_after}s).")

    # 3. Test Managed Background Task Queue
    print("\n--- 3. Testing Managed Background Task Queue ---")
    def sample_worker_job(x, y):
        time.sleep(0.05)
        return x * y

    job_id = task_queue.enqueue(sample_worker_job, 7, 8, name="Multiplication Worker Job")
    assert job_id.startswith("task_"), "Invalid job ID generated by task queue"
    print(f"✓ Test 3.1 PASS: Background task enqueued with ID: {job_id}")

    # Wait for completion (poll up to 1.5s)
    job_status = None
    for _ in range(15):
        time.sleep(0.1)
        job_status = task_queue.get_status(job_id)
        if job_status and job_status.get('status') == 'SUCCESS':
            break

    assert job_status is not None, "Task status query returned None"
    assert job_status.get('status') == 'SUCCESS', f"Task expected SUCCESS, got {job_status.get('status')}"
    print(f"✓ Test 3.2 PASS: Task queue worker executed job with SUCCESS status in {job_status.get('duration_seconds')}s.")

    # 4. Test Web Client Probes with Live Endpoints
    print("\n--- 4. Testing Live Web Endpoints with 100% Hardening ---")
    client = app.test_client()

    # Telemetry Health with Connection Pool info
    health_res = client.get('/api/v1/health')
    assert health_res.status_code == 200, f"/api/v1/health returned {health_res.status_code}"
    health_data = health_res.get_json()
    assert 'connection_pool' in health_data, "connection_pool missing from health check payload!"
    print(f"✓ Test 4.1 PASS: /api/v1/health reports pool telemetry: {health_data['connection_pool']}")

    # Telemetry Task Queue API
    tasks_res = client.get('/api/v1/tasks')
    assert tasks_res.status_code == 200, f"/api/v1/tasks returned {tasks_res.status_code}"
    tasks_data = tasks_res.get_json()
    assert tasks_data.get('status') == 'success' and len(tasks_data.get('tasks', [])) > 0, "No tasks reported by /api/v1/tasks"
    print(f"✓ Test 4.2 PASS: /api/v1/tasks reports {len(tasks_data['tasks'])} managed background tasks.")

    # Rate Limiter Protection on /login
    limiter.clear()
    for _ in range(10):
        client.post('/login', data={'username': 'attacker', 'password': 'bad'}, follow_redirects=False)
    # 11th request must trigger 429
    rate_limited_res = client.post('/login', data={'username': 'attacker', 'password': 'bad'}, follow_redirects=False)
    assert rate_limited_res.status_code == 429, f"Expected 429 Too Many Requests on /login, got {rate_limited_res.status_code}"
    assert 'Retry-After' in rate_limited_res.headers, "Retry-After header missing on 429 response"
    print("✓ Test 4.3 PASS: /login endpoint successfully enforced 429 Too Many Requests upon exceeding rate limit.")
    limiter.clear()

    print("\n=============================================================")
    print("ALL 100% ENTERPRISE HARDENING TESTS PASSED (100% SUCCESS)")
    print("=============================================================\n")

if __name__ == '__main__':
    run_tests()
